import type { DesignSystem } from '@/types/marketplace';

export type ExportFormat = 'css' | 'scss' | 'tailwind' | 'json';

interface ExportOptions {
  format: ExportFormat;
  includeComments?: boolean;
  darkMode?: boolean;
}

// Convert hex to HSL values
function hexToHsl(hex: string): { h: number; s: number; l: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  if (!result) return null;

  let r = parseInt(result[1], 16) / 255;
  let g = parseInt(result[2], 16) / 255;
  let b = parseInt(result[3], 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  let h = 0;
  let s = 0;
  const l = (max + min) / 2;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }

  return {
    h: Math.round(h * 360),
    s: Math.round(s * 100),
    l: Math.round(l * 100),
  };
}

function formatHsl(hex: string): string {
  const hsl = hexToHsl(hex);
  if (!hsl) return hex;
  return `${hsl.h} ${hsl.s}% ${hsl.l}%`;
}

// Generate CSS custom properties
export function exportAsCSS(system: DesignSystem, includeComments = true): string {
  const lines: string[] = [];
  
  if (includeComments) {
    lines.push(`/**`);
    lines.push(` * ${system.name} Design System`);
    lines.push(` * ${system.description || 'Generated by Kernel Builder'}`);
    lines.push(` * Generated: ${new Date().toISOString()}`);
    lines.push(` */`);
    lines.push('');
  }

  lines.push(':root {');

  // Colors
  if (includeComments) lines.push('  /* Colors */');
  if (system.colors) {
    const addColor = (name: string, value: string | { DEFAULT: string; foreground?: string }) => {
      if (typeof value === 'string') {
        lines.push(`  --${name}: ${formatHsl(value)};`);
      } else {
        lines.push(`  --${name}: ${formatHsl(value.DEFAULT)};`);
        if (value.foreground) {
          lines.push(`  --${name}-foreground: ${formatHsl(value.foreground)};`);
        }
      }
    };

    Object.entries(system.colors).forEach(([key, value]) => {
      addColor(key, value);
    });
  }

  lines.push('');

  // Typography
  if (includeComments) lines.push('  /* Typography */');
  if (system.typography?.fontFamily) {
    const { heading, body, mono } = system.typography.fontFamily;
    if (heading) lines.push(`  --font-heading: '${heading}', sans-serif;`);
    if (body) lines.push(`  --font-body: '${body}', sans-serif;`);
    if (mono) lines.push(`  --font-mono: '${mono}', monospace;`);
  }

  if (system.typography?.fontSize) {
    lines.push('');
    if (includeComments) lines.push('  /* Font Sizes */');
    Object.entries(system.typography.fontSize).forEach(([key, value]) => {
      lines.push(`  --text-${key}: ${value};`);
    });
  }

  if (system.typography?.fontWeight) {
    lines.push('');
    if (includeComments) lines.push('  /* Font Weights */');
    Object.entries(system.typography.fontWeight).forEach(([key, value]) => {
      lines.push(`  --font-${key}: ${value};`);
    });
  }

  if (system.typography?.lineHeight) {
    lines.push('');
    if (includeComments) lines.push('  /* Line Heights */');
    Object.entries(system.typography.lineHeight).forEach(([key, value]) => {
      lines.push(`  --leading-${key}: ${value};`);
    });
  }

  // Spacing
  if (system.spacing) {
    lines.push('');
    if (includeComments) lines.push('  /* Spacing */');
    lines.push(`  --spacing-unit: ${system.spacing.unit};`);
    if (system.spacing.scale) {
      system.spacing.scale.forEach((value, index) => {
        lines.push(`  --spacing-${index}: calc(var(--spacing-unit) * ${value});`);
      });
    }
  }

  // Shadows
  if (system.shadows) {
    lines.push('');
    if (includeComments) lines.push('  /* Shadows */');
    Object.entries(system.shadows).forEach(([key, value]) => {
      const varName = key === 'DEFAULT' ? 'shadow' : `shadow-${key}`;
      lines.push(`  --${varName}: ${value};`);
    });
  }

  // Border Radius
  if (system.border_radius) {
    lines.push('');
    if (includeComments) lines.push('  /* Border Radius */');
    Object.entries(system.border_radius).forEach(([key, value]) => {
      const varName = key === 'DEFAULT' ? 'radius' : `radius-${key}`;
      lines.push(`  --${varName}: ${value};`);
    });
  }

  lines.push('}');

  // Base element styles
  lines.push('');
  if (includeComments) lines.push('/* Base Element Styles */');
  if (system.typography?.fontFamily) {
    lines.push('body {');
    lines.push('  font-family: var(--font-body);');
    lines.push('  background-color: hsl(var(--background));');
    lines.push('  color: hsl(var(--foreground));');
    lines.push('}');
    lines.push('');
    lines.push('h1, h2, h3, h4, h5, h6 {');
    lines.push('  font-family: var(--font-heading);');
    lines.push('}');
    lines.push('');
    lines.push('code, pre, kbd {');
    lines.push('  font-family: var(--font-mono);');
    lines.push('}');
  }

  return lines.join('\n');
}

// Generate SCSS variables
export function exportAsSCSS(system: DesignSystem, includeComments = true): string {
  const lines: string[] = [];

  if (includeComments) {
    lines.push(`// ${system.name} Design System`);
    lines.push(`// ${system.description || 'Generated by Kernel Builder'}`);
    lines.push(`// Generated: ${new Date().toISOString()}`);
    lines.push('');
  }

  // Colors
  if (includeComments) lines.push('// Colors');
  if (system.colors) {
    Object.entries(system.colors).forEach(([key, value]) => {
      if (typeof value === 'string') {
        lines.push(`$${key}: ${value};`);
      } else {
        lines.push(`$${key}: ${value.DEFAULT};`);
        if (value.foreground) {
          lines.push(`$${key}-foreground: ${value.foreground};`);
        }
      }
    });
  }

  lines.push('');

  // Typography
  if (includeComments) lines.push('// Typography');
  if (system.typography?.fontFamily) {
    const { heading, body, mono } = system.typography.fontFamily;
    if (heading) lines.push(`$font-heading: '${heading}', sans-serif;`);
    if (body) lines.push(`$font-body: '${body}', sans-serif;`);
    if (mono) lines.push(`$font-mono: '${mono}', monospace;`);
  }

  if (system.typography?.fontSize) {
    lines.push('');
    if (includeComments) lines.push('// Font Sizes');
    lines.push('$font-sizes: (');
    Object.entries(system.typography.fontSize).forEach(([key, value], i, arr) => {
      lines.push(`  '${key}': ${value}${i < arr.length - 1 ? ',' : ''}`);
    });
    lines.push(');');
  }

  // Spacing
  if (system.spacing) {
    lines.push('');
    if (includeComments) lines.push('// Spacing');
    lines.push(`$spacing-unit: ${system.spacing.unit};`);
    if (system.spacing.scale) {
      lines.push('$spacing-scale: (');
      system.spacing.scale.forEach((value, index) => {
        lines.push(`  ${index}: $spacing-unit * ${value}${index < system.spacing.scale.length - 1 ? ',' : ''}`);
      });
      lines.push(');');
    }
  }

  // Shadows
  if (system.shadows) {
    lines.push('');
    if (includeComments) lines.push('// Shadows');
    lines.push('$shadows: (');
    const entries = Object.entries(system.shadows);
    entries.forEach(([key, value], i) => {
      lines.push(`  '${key}': ${value}${i < entries.length - 1 ? ',' : ''}`);
    });
    lines.push(');');
  }

  // Border Radius
  if (system.border_radius) {
    lines.push('');
    if (includeComments) lines.push('// Border Radius');
    lines.push('$radii: (');
    const entries = Object.entries(system.border_radius);
    entries.forEach(([key, value], i) => {
      lines.push(`  '${key}': ${value}${i < entries.length - 1 ? ',' : ''}`);
    });
    lines.push(');');
  }

  return lines.join('\n');
}

// Generate Tailwind config extend object
export function exportAsTailwind(system: DesignSystem): string {
  const extend: Record<string, unknown> = {};
  const config = {
    theme: {
      extend,
    },
  };

  // Colors
  if (system.colors) {
    const colors: Record<string, unknown> = {};
    Object.entries(system.colors).forEach(([key, value]) => {
      if (typeof value === 'string') {
        colors[key] = value;
      } else {
        colors[key] = {
          DEFAULT: value.DEFAULT,
          foreground: value.foreground,
        };
      }
    });
    extend.colors = colors;
  }

  // Typography
  if (system.typography?.fontFamily) {
    extend.fontFamily = {
      heading: [`'${system.typography.fontFamily.heading}'`, 'sans-serif'],
      body: [`'${system.typography.fontFamily.body}'`, 'sans-serif'],
      mono: [`'${system.typography.fontFamily.mono}'`, 'monospace'],
    };
  }

  if (system.typography?.fontSize) {
    extend.fontSize = system.typography.fontSize;
  }

  // Spacing
  if (system.spacing?.scale) {
    const spacing: Record<string, string> = {};
    system.spacing.scale.forEach((value, index) => {
      spacing[index.toString()] = `calc(${system.spacing.unit} * ${value})`;
    });
    extend.spacing = spacing;
  }

  // Shadows
  if (system.shadows) {
    extend.boxShadow = system.shadows;
  }

  // Border Radius
  if (system.border_radius) {
    extend.borderRadius = system.border_radius;
  }

  const output = [
    `/** @type {import('tailwindcss').Config} */`,
    `// ${system.name} - Tailwind CSS Configuration`,
    `// Merge this with your existing tailwind.config.ts`,
    '',
    `module.exports = ${JSON.stringify(config, null, 2)}`,
  ];

  return output.join('\n');
}

// Generate JSON tokens
export function exportAsJSON(system: DesignSystem): string {
  const tokens = {
    $schema: 'https://tr.designtokens.org/format/',
    name: system.name,
    description: system.description,
    generatedAt: new Date().toISOString(),
    tokens: {
      color: {} as Record<string, unknown>,
      typography: {} as Record<string, unknown>,
      spacing: {} as Record<string, unknown>,
      shadow: {} as Record<string, unknown>,
      borderRadius: {} as Record<string, unknown>,
    },
  };

  // Colors
  if (system.colors) {
    Object.entries(system.colors).forEach(([key, value]) => {
      if (typeof value === 'string') {
        tokens.tokens.color[key] = { $value: value, $type: 'color' };
      } else {
        tokens.tokens.color[key] = {
          default: { $value: value.DEFAULT, $type: 'color' },
          foreground: { $value: value.foreground, $type: 'color' },
        };
      }
    });
  }

  // Typography
  if (system.typography) {
    if (system.typography.fontFamily) {
      tokens.tokens.typography.fontFamily = {
        heading: { $value: system.typography.fontFamily.heading, $type: 'fontFamily' },
        body: { $value: system.typography.fontFamily.body, $type: 'fontFamily' },
        mono: { $value: system.typography.fontFamily.mono, $type: 'fontFamily' },
      };
    }
    if (system.typography.fontSize) {
      tokens.tokens.typography.fontSize = {};
      Object.entries(system.typography.fontSize).forEach(([key, value]) => {
        (tokens.tokens.typography.fontSize as Record<string, unknown>)[key] = {
          $value: value,
          $type: 'dimension',
        };
      });
    }
  }

  // Spacing
  if (system.spacing) {
    tokens.tokens.spacing.unit = { $value: system.spacing.unit, $type: 'dimension' };
    if (system.spacing.scale) {
      tokens.tokens.spacing.scale = system.spacing.scale.map((value, index) => ({
        index,
        $value: `calc(${system.spacing.unit} * ${value})`,
        $type: 'dimension',
      }));
    }
  }

  // Shadows
  if (system.shadows) {
    Object.entries(system.shadows).forEach(([key, value]) => {
      tokens.tokens.shadow[key] = { $value: value, $type: 'shadow' };
    });
  }

  // Border Radius
  if (system.border_radius) {
    Object.entries(system.border_radius).forEach(([key, value]) => {
      tokens.tokens.borderRadius[key] = { $value: value, $type: 'dimension' };
    });
  }

  return JSON.stringify(tokens, null, 2);
}

// Main export function
export function exportDesignTokens(system: DesignSystem, options: ExportOptions): string {
  switch (options.format) {
    case 'css':
      return exportAsCSS(system, options.includeComments);
    case 'scss':
      return exportAsSCSS(system, options.includeComments);
    case 'tailwind':
      return exportAsTailwind(system);
    case 'json':
      return exportAsJSON(system);
    default:
      return exportAsCSS(system, options.includeComments);
  }
}

// Download file helper
export function downloadTokensFile(content: string, filename: string, format: ExportFormat) {
  const mimeTypes: Record<ExportFormat, string> = {
    css: 'text/css',
    scss: 'text/x-scss',
    tailwind: 'application/javascript',
    json: 'application/json',
  };

  const extensions: Record<ExportFormat, string> = {
    css: 'css',
    scss: 'scss',
    tailwind: 'js',
    json: 'json',
  };

  const blob = new Blob([content], { type: mimeTypes[format] });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}.${extensions[format]}`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
