import { supabase } from '@/integrations/supabase/client';
import type { SecurityScanResult, SecurityFinding, SecuritySeverity } from '@/types/security';

const SCAN_CACHE_KEY = 'kernel_security_scan_cache';
const CACHE_DURATION_MS = 5 * 60 * 1000; // 5 minutes

interface CachedScan {
  result: SecurityScanResult;
  cachedAt: number;
}

export const securityService = {
  /**
   * Run a full security scan
   */
  async runScan(): Promise<SecurityScanResult> {
    const { data, error } = await supabase.functions.invoke('security-scan');
    
    if (error) {
      console.error('Security scan failed:', error);
      throw new Error(error.message || 'Failed to run security scan');
    }

    // Cache the result
    const cacheData: CachedScan = {
      result: data,
      cachedAt: Date.now(),
    };
    localStorage.setItem(SCAN_CACHE_KEY, JSON.stringify(cacheData));

    return data;
  },

  /**
   * Get cached scan result if available and not expired
   */
  getCachedScan(): SecurityScanResult | null {
    try {
      const cached = localStorage.getItem(SCAN_CACHE_KEY);
      if (!cached) return null;

      const { result, cachedAt }: CachedScan = JSON.parse(cached);
      
      // Check if cache is expired
      if (Date.now() - cachedAt > CACHE_DURATION_MS) {
        localStorage.removeItem(SCAN_CACHE_KEY);
        return null;
      }

      return result;
    } catch {
      return null;
    }
  },

  /**
   * Clear the cached scan
   */
  clearCache(): void {
    localStorage.removeItem(SCAN_CACHE_KEY);
  },

  /**
   * Get severity counts from findings
   */
  getSeverityCounts(findings: SecurityFinding[]): Record<SecuritySeverity, number> {
    return {
      critical: findings.filter(f => f.severity === 'critical').length,
      high: findings.filter(f => f.severity === 'high').length,
      medium: findings.filter(f => f.severity === 'medium').length,
      low: findings.filter(f => f.severity === 'low').length,
      info: findings.filter(f => f.severity === 'info').length,
    };
  },

  /**
   * Get overall security grade (A-F)
   */
  getSecurityGrade(scanResult: SecurityScanResult): { grade: string; color: string; description: string } {
    const { summary } = scanResult;
    
    if (summary.critical > 0) {
      return { 
        grade: 'F', 
        color: 'text-red-500', 
        description: 'Critical vulnerabilities detected' 
      };
    }
    
    if (summary.high > 2) {
      return { 
        grade: 'D', 
        color: 'text-orange-500', 
        description: 'Multiple high-severity issues' 
      };
    }
    
    if (summary.high > 0 || summary.medium > 3) {
      return { 
        grade: 'C', 
        color: 'text-yellow-500', 
        description: 'Some security improvements needed' 
      };
    }
    
    if (summary.medium > 0 || summary.low > 2) {
      return { 
        grade: 'B', 
        color: 'text-blue-500', 
        description: 'Good security with minor issues' 
      };
    }
    
    return { 
      grade: 'A', 
      color: 'text-green-500', 
      description: 'Excellent security posture' 
    };
  },

  /**
   * Generate remediation SQL for all critical/high findings
   */
  generateRemediationScript(findings: SecurityFinding[]): string {
    const criticalAndHigh = findings.filter(
      f => f.severity === 'critical' || f.severity === 'high'
    );

    if (criticalAndHigh.length === 0) {
      return '-- No critical or high severity issues to remediate';
    }

    const lines = [
      '-- Security Remediation Script',
      '-- Generated by Kernel Security Scanner',
      `-- Date: ${new Date().toISOString()}`,
      '',
      '-- WARNING: Review each statement before executing!',
      '',
    ];

    for (const finding of criticalAndHigh) {
      lines.push(`-- [${finding.severity.toUpperCase()}] ${finding.title}`);
      lines.push(`-- Table: ${finding.tableName}`);
      lines.push(finding.remediation);
      lines.push('');
    }

    return lines.join('\n');
  },

  /**
   * Export scan results as JSON
   */
  exportAsJSON(scanResult: SecurityScanResult): string {
    return JSON.stringify(scanResult, null, 2);
  },

  /**
   * Download scan report
   */
  downloadReport(scanResult: SecurityScanResult, format: 'json' | 'sql' = 'json'): void {
    let content: string;
    let filename: string;
    let mimeType: string;

    if (format === 'sql') {
      content = this.generateRemediationScript(scanResult.findings);
      filename = `security-remediation-${scanResult.scanId}.sql`;
      mimeType = 'text/plain';
    } else {
      content = this.exportAsJSON(scanResult);
      filename = `security-scan-${scanResult.scanId}.json`;
      mimeType = 'application/json';
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  },
};
